"use strict";
let fruits = ['apple', 'banana', 'lemon', 'coconuts'];
console.log(fruits);
let cars = ['gol', 'duster oroch', 'tracker', 'a3', 'saveiro'];
console.log(cars);
let numberList = [0, 1, 2, 3, 4, 5];
numberList = [...numberList, 6, 7, 8, 9];
console.log(numberList);
let programmingLanguages = new Array('JavaScript', 'PHP', 'Python', 'JAVA');
console.log(programmingLanguages);
